### ISSUE TITLE
Text bug in contests

### ISSUE THREAD

**Issue by Anfeket** [cfpwastaken/edupageAddons#1]
The contest tab is broken, text color is the same as background
![image](https://user-images.githubusercontent.com/83760348/158355170-e328d26c-1b03-4829-a630-c9e835334c37.png)

**Comment by cfpwastaken** [comment]
The dark theme is not finished yet as seen here. Unfortunately my school does not have this tab so I can not fix it.

**Comment by cfpwastaken** [comment]
Feel free to reopen this issue if you found a way for me to test this.
